# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoreModule' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking', '3.2.1'
  pod 'YYCache', '1.0.4'
  pod 'Mantle', '2.1.0'
  # Pods for CoreModule

  target 'CoreModuleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
